previewsEnabled: true
services:
  - type: web
    name: atiun-server
    runtime: image
    autoDeploy: false
    image:
      url: docker.io/library/nginx:latest
    envVars:
      - key: ATUIN_HOST
        value: 0.0.0.0
      - key: ATUIN_OPEN_REGISTRATION
        value: true # change to true to allow registrations
      - key: ATUIN_DB_URI
        fromDatabase:
          name: atuin-db
          property: connectionString

databases:
  - name: atuin-db
    databaseName: private
    ipAllowList: []
